//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuPhong
    {
        public int ID { get; set; }
        public Nullable<int> ID_ChiTietGiaoDich { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual ChiTietGiaoDich ChiTietGiaoDich { get; set; }
    }
}
