//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HOLYBIRDRESORTEntities : DbContext
    {
        public HOLYBIRDRESORTEntities()
            : base("name=HOLYBIRDRESORTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietGiaoDich> ChiTietGiaoDiches { get; set; }
        public virtual DbSet<DichVuPhong> DichVuPhongs { get; set; }
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<HeThong> HeThongs { get; set; }
        public virtual DbSet<HinhThuc> HinhThucs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiHeThong> LoaiHeThongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<TinhTrangGiaoDich> TinhTrangGiaoDiches { get; set; }
        public virtual DbSet<TrangThaiPhong> TrangThaiPhongs { get; set; }
    
        public virtual int sp_CapNhatChiTietGiaoDich(Nullable<int> id, Nullable<int> idGiaoDich, Nullable<int> idPhong, Nullable<int> idKhach, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            var idPhongParameter = idPhong.HasValue ?
                new ObjectParameter("idPhong", idPhong) :
                new ObjectParameter("idPhong", typeof(int));
    
            var idKhachParameter = idKhach.HasValue ?
                new ObjectParameter("idKhach", idKhach) :
                new ObjectParameter("idKhach", typeof(int));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("ngayBatDau", ngayBatDau) :
                new ObjectParameter("ngayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("ngayKetThuc", ngayKetThuc) :
                new ObjectParameter("ngayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatChiTietGiaoDich", idParameter, idGiaoDichParameter, idPhongParameter, idKhachParameter, ngayBatDauParameter, ngayKetThucParameter);
        }
    
        public virtual int sp_CapNhatTinhTrangGiaoDich(Nullable<int> idDoan, Nullable<int> idTinhTrang)
        {
            var idDoanParameter = idDoan.HasValue ?
                new ObjectParameter("idDoan", idDoan) :
                new ObjectParameter("idDoan", typeof(int));
    
            var idTinhTrangParameter = idTinhTrang.HasValue ?
                new ObjectParameter("idTinhTrang", idTinhTrang) :
                new ObjectParameter("idTinhTrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTinhTrangGiaoDich", idDoanParameter, idTinhTrangParameter);
        }
    
        public virtual ObjectResult<sp_ChiTietGiaoDich_Result> sp_ChiTietGiaoDich(Nullable<int> idDoan)
        {
            var idDoanParameter = idDoan.HasValue ?
                new ObjectParameter("idDoan", idDoan) :
                new ObjectParameter("idDoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietGiaoDich_Result>("sp_ChiTietGiaoDich", idDoanParameter);
        }
    
        public virtual int sp_KhoiTaoDanhSachPhong(Nullable<int> roomInAFloor, Nullable<int> totalFloor)
        {
            var roomInAFloorParameter = roomInAFloor.HasValue ?
                new ObjectParameter("roomInAFloor", roomInAFloor) :
                new ObjectParameter("roomInAFloor", typeof(int));
    
            var totalFloorParameter = totalFloor.HasValue ?
                new ObjectParameter("totalFloor", totalFloor) :
                new ObjectParameter("totalFloor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhoiTaoDanhSachPhong", roomInAFloorParameter, totalFloorParameter);
        }
    
        public virtual ObjectResult<ChiTietGiaoDich> sp_LayChiTietGiaoDichTheoDoan(Nullable<int> idDoan)
        {
            var idDoanParameter = idDoan.HasValue ?
                new ObjectParameter("idDoan", idDoan) :
                new ObjectParameter("idDoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietGiaoDich>("sp_LayChiTietGiaoDichTheoDoan", idDoanParameter);
        }
    
        public virtual ObjectResult<ChiTietGiaoDich> sp_LayChiTietGiaoDichTheoDoan(Nullable<int> idDoan, MergeOption mergeOption)
        {
            var idDoanParameter = idDoan.HasValue ?
                new ObjectParameter("idDoan", idDoan) :
                new ObjectParameter("idDoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietGiaoDich>("sp_LayChiTietGiaoDichTheoDoan", mergeOption, idDoanParameter);
        }
    
        public virtual ObjectResult<sp_LayDanhSachDoan_Result> sp_LayDanhSachDoan(Nullable<int> idDoan)
        {
            var idDoanParameter = idDoan.HasValue ?
                new ObjectParameter("idDoan", idDoan) :
                new ObjectParameter("idDoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachDoan_Result>("sp_LayDanhSachDoan", idDoanParameter);
        }
    
        public virtual ObjectResult<sp_LayThongTinDoan_Result> sp_LayThongTinDoan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinDoan_Result>("sp_LayThongTinDoan", idParameter);
        }
    
        public virtual ObjectResult<sp_LayThongTinPhong_Result> sp_LayThongTinPhong(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinPhong_Result>("sp_LayThongTinPhong", idParameter);
        }
    
        public virtual ObjectResult<sp_SearchAvailableRoom_Result> sp_SearchAvailableRoom(Nullable<int> floor, Nullable<int> state, Nullable<int> level, Nullable<int> numberslot, string datestart, string dateend)
        {
            var floorParameter = floor.HasValue ?
                new ObjectParameter("floor", floor) :
                new ObjectParameter("floor", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var numberslotParameter = numberslot.HasValue ?
                new ObjectParameter("numberslot", numberslot) :
                new ObjectParameter("numberslot", typeof(int));
    
            var datestartParameter = datestart != null ?
                new ObjectParameter("datestart", datestart) :
                new ObjectParameter("datestart", typeof(string));
    
            var dateendParameter = dateend != null ?
                new ObjectParameter("dateend", dateend) :
                new ObjectParameter("dateend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchAvailableRoom_Result>("sp_SearchAvailableRoom", floorParameter, stateParameter, levelParameter, numberslotParameter, datestartParameter, dateendParameter);
        }
    
        public virtual int sp_ThemChiTietGiaoDich(Nullable<int> idGiaoDich, Nullable<int> idPhong, Nullable<int> idKhach, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            var idPhongParameter = idPhong.HasValue ?
                new ObjectParameter("idPhong", idPhong) :
                new ObjectParameter("idPhong", typeof(int));
    
            var idKhachParameter = idKhach.HasValue ?
                new ObjectParameter("idKhach", idKhach) :
                new ObjectParameter("idKhach", typeof(int));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("ngayBatDau", ngayBatDau) :
                new ObjectParameter("ngayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("ngayKetThuc", ngayKetThuc) :
                new ObjectParameter("ngayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChiTietGiaoDich", idGiaoDichParameter, idPhongParameter, idKhachParameter, ngayBatDauParameter, ngayKetThucParameter);
        }
    
        public virtual int sp_XoaChiTietGiaoDich(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChiTietGiaoDich", idParameter);
        }
    
        public virtual int sp_XoaChiTietGiaoDichTheoDoan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChiTietGiaoDichTheoDoan", idParameter);
        }
    
        public virtual int sp_CapNhatIDTruongDoanChoGiaoDich(Nullable<int> idtruongdoan, Nullable<int> id_giaodich)
        {
            var idtruongdoanParameter = idtruongdoan.HasValue ?
                new ObjectParameter("idtruongdoan", idtruongdoan) :
                new ObjectParameter("idtruongdoan", typeof(int));
    
            var id_giaodichParameter = id_giaodich.HasValue ?
                new ObjectParameter("id_giaodich", id_giaodich) :
                new ObjectParameter("id_giaodich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatIDTruongDoanChoGiaoDich", idtruongdoanParameter, id_giaodichParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LayIDKhachHangTheoCMND(string cmnd)
        {
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LayIDKhachHangTheoCMND", cmndParameter);
        }
    
        public virtual int sp_LuuThongTinKhachHang(Nullable<int> id_giaodich, string hoten, string cmnd)
        {
            var id_giaodichParameter = id_giaodich.HasValue ?
                new ObjectParameter("id_giaodich", id_giaodich) :
                new ObjectParameter("id_giaodich", typeof(int));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LuuThongTinKhachHang", id_giaodichParameter, hotenParameter, cmndParameter);
        }
    
        public virtual int sp_TaoMoiGiaoDich(string madoan, string tendangnhap, string matkhau, Nullable<int> songuoi, Nullable<int> sophong, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc, Nullable<int> tinhtrang, Nullable<int> tongtien)
        {
            var madoanParameter = madoan != null ?
                new ObjectParameter("madoan", madoan) :
                new ObjectParameter("madoan", typeof(string));
    
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var songuoiParameter = songuoi.HasValue ?
                new ObjectParameter("songuoi", songuoi) :
                new ObjectParameter("songuoi", typeof(int));
    
            var sophongParameter = sophong.HasValue ?
                new ObjectParameter("sophong", sophong) :
                new ObjectParameter("sophong", typeof(int));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoMoiGiaoDich", madoanParameter, tendangnhapParameter, matkhauParameter, songuoiParameter, sophongParameter, ngaybatdauParameter, ngayketthucParameter, tinhtrangParameter, tongtienParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TimIDGiaoDichTheoCMNDTruongDoan(string cmnd)
        {
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TimIDGiaoDichTheoCMNDTruongDoan", cmndParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayGiaoDichTheoMaDoan(string maDoan)
        {
            var maDoanParameter = maDoan != null ?
                new ObjectParameter("maDoan", maDoan) :
                new ObjectParameter("maDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayGiaoDichTheoMaDoan", maDoanParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayGiaoDichTheoMaDoan(string maDoan, MergeOption mergeOption)
        {
            var maDoanParameter = maDoan != null ?
                new ObjectParameter("maDoan", maDoan) :
                new ObjectParameter("maDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayGiaoDichTheoMaDoan", mergeOption, maDoanParameter);
        }
    
        public virtual ObjectResult<ChiTietGiaoDich> sp_LayChiTietGiaoDichTheoIdGiaoDich(Nullable<int> idGiaoDich)
        {
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietGiaoDich>("sp_LayChiTietGiaoDichTheoIdGiaoDich", idGiaoDichParameter);
        }
    
        public virtual ObjectResult<ChiTietGiaoDich> sp_LayChiTietGiaoDichTheoIdGiaoDich(Nullable<int> idGiaoDich, MergeOption mergeOption)
        {
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietGiaoDich>("sp_LayChiTietGiaoDichTheoIdGiaoDich", mergeOption, idGiaoDichParameter);
        }
    
        public virtual int sp_CapNhatTrangThaiPhong(Nullable<int> idPhong, Nullable<int> idTrangThai)
        {
            var idPhongParameter = idPhong.HasValue ?
                new ObjectParameter("idPhong", idPhong) :
                new ObjectParameter("idPhong", typeof(int));
    
            var idTrangThaiParameter = idTrangThai.HasValue ?
                new ObjectParameter("idTrangThai", idTrangThai) :
                new ObjectParameter("idTrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTrangThaiPhong", idPhongParameter, idTrangThaiParameter);
        }
    
        public virtual int sp_XoaGiaoDich(Nullable<int> idGiaoDich)
        {
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaGiaoDich", idGiaoDichParameter);
        }
    
        public virtual int sp_XoaDichVuPhong(Nullable<int> idChiTietGiaoDich)
        {
            var idChiTietGiaoDichParameter = idChiTietGiaoDich.HasValue ?
                new ObjectParameter("idChiTietGiaoDich", idChiTietGiaoDich) :
                new ObjectParameter("idChiTietGiaoDich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaDichVuPhong", idChiTietGiaoDichParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayTatCaGiaoDich()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayTatCaGiaoDich");
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayTatCaGiaoDich(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayTatCaGiaoDich", mergeOption);
        }
    
        public virtual ObjectResult<TinhTrangGiaoDich> sp_LayTinhTrangGiaoDich(Nullable<int> idTinhTrang)
        {
            var idTinhTrangParameter = idTinhTrang.HasValue ?
                new ObjectParameter("idTinhTrang", idTinhTrang) :
                new ObjectParameter("idTinhTrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinhTrangGiaoDich>("sp_LayTinhTrangGiaoDich", idTinhTrangParameter);
        }
    
        public virtual ObjectResult<TinhTrangGiaoDich> sp_LayTinhTrangGiaoDich(Nullable<int> idTinhTrang, MergeOption mergeOption)
        {
            var idTinhTrangParameter = idTinhTrang.HasValue ?
                new ObjectParameter("idTinhTrang", idTinhTrang) :
                new ObjectParameter("idTinhTrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinhTrangGiaoDich>("sp_LayTinhTrangGiaoDich", mergeOption, idTinhTrangParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_TimKiemGiaoDich(string maDoan)
        {
            var maDoanParameter = maDoan != null ?
                new ObjectParameter("maDoan", maDoan) :
                new ObjectParameter("maDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_TimKiemGiaoDich", maDoanParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_TimKiemGiaoDich(string maDoan, MergeOption mergeOption)
        {
            var maDoanParameter = maDoan != null ?
                new ObjectParameter("maDoan", maDoan) :
                new ObjectParameter("maDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_TimKiemGiaoDich", mergeOption, maDoanParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayGiaoDichTheoMaDoanDayDu(string maDoan)
        {
            var maDoanParameter = maDoan != null ?
                new ObjectParameter("maDoan", maDoan) :
                new ObjectParameter("maDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayGiaoDichTheoMaDoanDayDu", maDoanParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayGiaoDichTheoMaDoanDayDu(string maDoan, MergeOption mergeOption)
        {
            var maDoanParameter = maDoan != null ?
                new ObjectParameter("maDoan", maDoan) :
                new ObjectParameter("maDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayGiaoDichTheoMaDoanDayDu", mergeOption, maDoanParameter);
        }
    
        public virtual ObjectResult<Phong> sp_LayPhongTheoMaPhong(string maPhong)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Phong>("sp_LayPhongTheoMaPhong", maPhongParameter);
        }
    
        public virtual ObjectResult<Phong> sp_LayPhongTheoMaPhong(string maPhong, MergeOption mergeOption)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Phong>("sp_LayPhongTheoMaPhong", mergeOption, maPhongParameter);
        }
    
        public virtual int sp_CapNhatChiTietGiaoDichKhiThanhToan(Nullable<int> idGiaoDichThanhToan, Nullable<int> idMaPhong, Nullable<int> thanhTien)
        {
            var idGiaoDichThanhToanParameter = idGiaoDichThanhToan.HasValue ?
                new ObjectParameter("idGiaoDichThanhToan", idGiaoDichThanhToan) :
                new ObjectParameter("idGiaoDichThanhToan", typeof(int));
    
            var idMaPhongParameter = idMaPhong.HasValue ?
                new ObjectParameter("idMaPhong", idMaPhong) :
                new ObjectParameter("idMaPhong", typeof(int));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("thanhTien", thanhTien) :
                new ObjectParameter("thanhTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatChiTietGiaoDichKhiThanhToan", idGiaoDichThanhToanParameter, idMaPhongParameter, thanhTienParameter);
        }
    
        public virtual int sp_CapNhatTongTienGiaoDich(Nullable<int> idGiaoDich, Nullable<int> tongTien)
        {
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTongTienGiaoDich", idGiaoDichParameter, tongTienParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayGiaoDichTheoId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayGiaoDichTheoId", idParameter);
        }
    
        public virtual ObjectResult<GiaoDich> sp_LayGiaoDichTheoId(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoDich>("sp_LayGiaoDichTheoId", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_LayTenNguoiDaiDienTheoId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_LayTenNguoiDaiDienTheoId", idParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_LayTenNguoiDaiDienTheoId(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_LayTenNguoiDaiDienTheoId", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<ChiTietGiaoDich> sp_LayChiTietGiaoDichTheoIdPhong(Nullable<int> idPhong, Nullable<int> idGiaoDich)
        {
            var idPhongParameter = idPhong.HasValue ?
                new ObjectParameter("idPhong", idPhong) :
                new ObjectParameter("idPhong", typeof(int));
    
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietGiaoDich>("sp_LayChiTietGiaoDichTheoIdPhong", idPhongParameter, idGiaoDichParameter);
        }
    
        public virtual ObjectResult<ChiTietGiaoDich> sp_LayChiTietGiaoDichTheoIdPhong(Nullable<int> idPhong, Nullable<int> idGiaoDich, MergeOption mergeOption)
        {
            var idPhongParameter = idPhong.HasValue ?
                new ObjectParameter("idPhong", idPhong) :
                new ObjectParameter("idPhong", typeof(int));
    
            var idGiaoDichParameter = idGiaoDich.HasValue ?
                new ObjectParameter("idGiaoDich", idGiaoDich) :
                new ObjectParameter("idGiaoDich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietGiaoDich>("sp_LayChiTietGiaoDichTheoIdPhong", mergeOption, idPhongParameter, idGiaoDichParameter);
        }
    }
}
