//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeThong
    {
        public HeThong()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int ID { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> ID_LoaiHeThong { get; set; }
    
        public virtual LoaiHeThong LoaiHeThong { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
