//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.ChiTietGiaoDiches = new HashSet<ChiTietGiaoDich>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_GiaoDich { get; set; }
        public string HoTen { get; set; }
        public string CMND { get; set; }
    
        public virtual ICollection<ChiTietGiaoDich> ChiTietGiaoDiches { get; set; }
        public virtual GiaoDich GiaoDich { get; set; }
    }
}
