//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManageHotelEntities : DbContext
    {
        public ManageHotelEntities()
            : base("name=ManageHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietGiaoDich> ChiTietGiaoDiches { get; set; }
        public virtual DbSet<DichVuPhong> DichVuPhongs { get; set; }
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<HeThong> HeThongs { get; set; }
        public virtual DbSet<HinhThuc> HinhThucs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiHeThong> LoaiHeThongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<TinhTrangGiaoDich> TinhTrangGiaoDiches { get; set; }
        public virtual DbSet<TrangThaiPhong> TrangThaiPhongs { get; set; }
    }
}
